In [ ]:
import pandas as pd
import numpy as np
import numpy as np
from sklearn.model_selection import train_test_split


import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [ ]:
!wget -P /content/drive/MyDrive/ML_ZoomCamp/2_Week/ML_ZoomCamp_Hw2 https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-24 10:48:14--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘/content/drive/MyDrive/ML_ZoomCamp/2_Week/ML_ZoomCamp_Hw2/housing.csv.8’

housing.csv.8       100%[===================>]   1.36M  --.-KB/s    in 0.07s

2023-09-24 10:48:15 (18.5 MB/s) - ‘/content/drive/MyDrive/ML_ZoomCamp/2_Week/ML_ZoomCamp_Hw2/housing.csv.8’ saved [1423529/1423529]

In [ ]:
df = pd.read_csv('housing.csv')
len(df)

20640

In [ ]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [ ]:
df[df['ocean_proximity'] == '<1H OCEAN']

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
701,-121.97,37.64,32.0,1283.0,194.0,485.0,171.0,6.0574,431000.0,<1H OCEAN
830,-121.99,37.61,9.0,3666.0,711.0,2341.0,703.0,4.6458,217000.0,<1H OCEAN
859,-121.97,37.57,21.0,4342.0,783.0,2172.0,789.0,4.6146,247600.0,<1H OCEAN
860,-121.96,37.58,15.0,3575.0,597.0,1777.0,559.0,5.7192,283500.0,<1H OCEAN
861,-121.98,37.58,20.0,4126.0,1031.0,2079.0,975.0,3.6832,216900.0,<1H OCEAN
...,...,...,...,...,...,...,...,...,...,...
20502,-118.68,34.33,45.0,121.0,25.0,67.0,27.0,2.9821,325000.0,<1H OCEAN
20503,-118.75,34.33,27.0,534.0,85.0,243.0,77.0,8.2787,330000.0,<1H OCEAN
20504,-118.73,34.29,11.0,5451.0,736.0,2526.0,752.0,7.3550,343900.0,<1H OCEAN
20505,-118.72,34.29,22.0,3266.0,529.0,1595.0,494.0,6.0368,248000.0,<1H OCEAN
20506,-118.73,34.29,8.0,4983.0,754.0,2510.0,725.0,6.9454,276500.0,<1H OCEAN

In [ ]:
df_v0 = df[df['ocean_proximity'].isin(['<1H OCEAN', 'INLAND'])]

In [ ]:
df_v0

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
701,-121.97,37.64,32.0,1283.0,194.0,485.0,171.0,6.0574,431000.0,<1H OCEAN
830,-121.99,37.61,9.0,3666.0,711.0,2341.0,703.0,4.6458,217000.0,<1H OCEAN
859,-121.97,37.57,21.0,4342.0,783.0,2172.0,789.0,4.6146,247600.0,<1H OCEAN
860,-121.96,37.58,15.0,3575.0,597.0,1777.0,559.0,5.7192,283500.0,<1H OCEAN
861,-121.98,37.58,20.0,4126.0,1031.0,2079.0,975.0,3.6832,216900.0,<1H OCEAN
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [ ]:
df_v1 = df_v0[['latitude', 'longitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value']]

In [ ]:
df_v1.head()

,latitude,longitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
701,37.64,-121.97,32.0,1283.0,194.0,485.0,171.0,6.0574,431000.0
830,37.61,-121.99,9.0,3666.0,711.0,2341.0,703.0,4.6458,217000.0
859,37.57,-121.97,21.0,4342.0,783.0,2172.0,789.0,4.6146,247600.0
860,37.58,-121.96,15.0,3575.0,597.0,1777.0,559.0,5.7192,283500.0
861,37.58,-121.98,20.0,4126.0,1031.0,2079.0,975.0,3.6832,216900.0

In [ ]:
missing_values = df_v1.isnull().sum()

print(missing_values)

latitude                0
longitude               0
housing_median_age      0
total_rooms             0
total_bedrooms        157
population              0
households              0
median_income           0
median_house_value      0
dtype: int64

### Question 2

In [ ]:
median_population = df_v1['population'].median()

print("Median population:", median_population)

Median population: 1195.0

### Question 3

In [ ]:
# Shuffle the dataset with a seed of 42
shuffled_data = df_v1.sample(frac=1, random_state=42)

# Split the data into train/val/test sets with a 60%/20%/20% distribution
train_ratio = 0.6
val_ratio = 0.2
test_ratio = 0.2

df_train, temp_data = train_test_split(shuffled_data, test_size=1 - train_ratio, random_state=42)
df_val, df_test = train_test_split(temp_data, test_size=test_ratio / (test_ratio + val_ratio), random_state=42)

# Apply log transformation to the 'median_house_value' variable
y_train= np.log1p(df_train['median_house_value'])
y_val = np.log1p(df_val['median_house_value'])
y_test = np.log1p(df_test['median_house_value'])

del df_train['median_house_value']
del df_val['median_house_value']
del df_test['median_house_value']

In [ ]:
#Linear Regression
def train_linear_regression(X, y):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    XTX_inv = np.linalg.inv(XTX)
    w = XTX_inv.dot(X.T).dot(y)

    return w[0], w[1:]


#RMSE
def rmse(y, y_pred):
    error = y_pred - y
    mse = (error ** 2).mean()
    return np.sqrt(mse)

In [ ]:
# Computing the trainin mean
total_bedrooms_mean_value = df_train['total_bedrooms'].mean()
total_bedrooms_mean_value

543.4965102544829

In [ ]:
def prepare_data(df, mean_replace_value=None):
    df_temp = df.copy()
    if mean_replace_value is None:
        X = df_temp.values

    else:
        df_temp['total_bedrooms'] = df_temp['total_bedrooms'].fillna(mean_replace_value)
        X = df_temp.values
        #print(replace_value)

    return X

In [ ]:
X_train = prepare_data(df_train, 0)
w0, w = train_linear_regression(X_train, y_train)

X_val = prepare_data(df_val, 0)
y_pred = w0 + X_val.dot(w)
rmse_zero_fill = round(rmse(y_val, y_pred), 2)
rmse_zero_fill

0.35

In [ ]:
X_train = prepare_data(df_train, total_bedrooms_mean_value)
w0, w = train_linear_regression(X_train, y_train)

X_val = prepare_data(df_val, total_bedrooms_mean_value)
y_pred = w0 + X_val.dot(w)
rmse_mean_fill = round(rmse(y_val, y_pred), 2)
rmse_mean_fill

0.35

### Question 4

In [ ]:
#Regularization
def train_linear_regression_reg(X, y, r=0.0):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    reg = r * np.eye(XTX.shape[0])
    XTX = XTX + reg

    XTX_inv = np.linalg.inv(XTX)
    w = XTX_inv.dot(X.T).dot(y)

    return w[0], w[1:]

In [ ]:
X_train = prepare_data(df_train,0)

In [ ]:
for r in [0, 0.000001, 0.0001, 0.001, 0.01, 0.1, 1, 5, 10]:
    w_0, w = train_linear_regression_reg(X_train, y_train, r=r)
    print(r,round( w_0,2))

0 -9.81
1e-06 -9.81
0.0001 -9.81
0.001 -9.79
0.01 -9.61
0.1 -8.1
1 -3.15
5 -0.84
10 -0.44

In [ ]:
results = dict()
X_train = prepare_data(df_train, 0)
X_val = prepare_data(df_val, 0)
best_rmse = None
best_rmse_arg = None

for r in [0, 0.000001, 0.0001, 0.001, 0.01, 0.1, 1, 5, 10]:
    w_0, w = train_linear_regression_reg(X_train, y_train, r=r)
    y_pred = w_0 + X_val.dot(w)
    print('%6s' %r, rmse(y_val, y_pred))
    raw_rmse = rmse(y_val, y_pred)
    if best_rmse is None:
        best_rmse = raw_rmse
        best_rmse_arg = r
    elif raw_rmse < best_rmse:
        best_rmse = raw_rmse
        best_rmse_arg = r
    results[r] = round(raw_rmse, 2)


print(f"[ANSWER-4] Best RMSE is {best_rmse} for r value: {best_rmse_arg}")

     0 0.34646080984455857
 1e-06 0.34646081267117673
0.0001 0.346461092789198
 0.001 0.346463662954219
  0.01 0.346491599518432
   0.1 0.34691467894748573
     1 0.3506829863431153
     5 0.3536566602576598
    10 0.3542594702285465
[ANSWER-4] Best RMSE is 0.34646080984455857 for r value: 0

### Question 5

In [ ]:
X_train

array([[  35.13  , -120.66  ,   41.    , ...,  940.    ,  507.    ,
           1.9653],
       [  35.26  , -118.95  ,   24.    , ...,  667.    ,  184.    ,
           4.    ],
       [  36.77  , -119.68  ,   21.    , ...,  583.    ,  205.    ,
           6.0132],
       ...,
       [  34.15  , -118.09  ,   52.    , ...,  268.    ,  110.    ,
           3.5568],
       [  38.58  , -121.31  ,   10.    , ...,  962.    ,  497.    ,
           2.5035],
       [  38.94  , -122.69  ,    9.    , ...,  517.    ,  187.    ,
           3.125 ]])

In [ ]:
scores = list()
n = len(df_v1)
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test

for seed in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]:
    idx = np.arange(n)
    np.random.seed(seed)
    np.random.shuffle(idx)

    # split dataset into 3 parts
    df_train = df_v1.iloc[idx[:n_train]]
    df_val = df_v1.iloc[idx[n_train:n_train + n_val]]
    df_test = df_v1.iloc[idx[n_train + n_val:]]



    # reset indexes
    df_train = df_train.reset_index(drop=True)
    df_val = df_val.reset_index(drop=True)
    df_test = df_test.reset_index(drop=True)

    # Apply log transformation to the 'median_house_value' variable
    y_train= np.log1p(df_train['median_house_value'])
    y_val = np.log1p(df_val['median_house_value'])
    y_test = np.log1p(df_test['median_house_value'])


    # drop target variable from the dataset
    del df_train['median_house_value']
    del df_val['median_house_value']
    del df_test['median_house_value']


    X_train_seed = prepare_data(df_train, 0)

    w0, w = train_linear_regression(X_train_seed, y_train)

    X_val_seed = prepare_data(df_val, 0)
    y_pred = w0 + X_val_seed.dot(w)
    scores.append(rmse(y_val, y_pred))
    print('for seed =', seed, 'score =', scores[seed], '\n')


print(f"[ANSWER-5] The standard deviation of all the scores is: {round(np.std(scores), 3)}")

for seed = 0 score = 0.33773871600429795

for seed = 1 score = 0.3377999353665367

for seed = 2 score = 0.33842870067535874

for seed = 3 score = 0.33200494683039145

for seed = 4 score = 0.33944518625559017

for seed = 5 score = 0.34338197052661196

for seed = 6 score = 0.33853302117699696

for seed = 7 score = 0.34687476972995035

for seed = 8 score = 0.35127368659627567

for seed = 9 score = 0.3341558266520752

[ANSWER-5] The standard deviation of all the scores is: 0.005

### Question 6

In [ ]:
n = len(df_v1)
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test

idx = np.arange(n)
np.random.seed(9)
np.random.shuffle(idx)

df_train = df_v1.iloc[idx[:n_train+n_val]]
df_test = df_v1.iloc[idx[n_train+n_val:]]

df_train = df_train.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = np.log1p(df_train.median_house_value.values)
y_test = np.log1p(df_test.median_house_value.values)

del df_train['median_house_value']
del df_test['median_house_value']

X_train = prepare_data(df_train, 0)
w0, w = train_linear_regression_reg(X_train, y_train, r=0.001)

X_test = prepare_data(df_test, 0)
y_pred = w0 + X_test.dot(w)


print(f"[ANSWER-6] The RMSE score in test dataset is: {round(rmse(y_test, y_pred), 2)}")

[ANSWER-6] The RMSE score in test dataset is: 0.33